Add mode to convert 'ALL' quodlibet playlists to m3u

diff --git a/.local/bin/exportplaylist b/.local/bin/exportplaylist
--- a/.local/bin/exportplaylist
+++ b/.local/bin/exportplaylist
@@ -5,12 +5,17 @@
 QL_PLAYLIST_PATH="$HOME/.config/quodlibet/playlists"
 BASE_MUSIC_PATH="/mnt/data/Music"
 
-[ -z "$1" ] && echo "Provide a playlist name" && exit 1
+[ -z "$1" ] && echo "Provide a playlist names or simply 'ALL'" && exit 1
 
-PLAYLIST_PATH="$QL_PLAYLIST_PATH/$1.xspf"
-[ ! -f "$PLAYLIST_PATH" ] && echo "Invalid playlist" && exit 1
-OUTPUT_PATH="$BASE_MUSIC_PATH/Playlists/$1.m3u"
+xs=$@
+[ "$1" = "ALL" ] && xs=$(cd "$QL_PLAYLIST_PATH" && find . -type f -name '*.xspf' -exec basename {} .xspf ';')
 
-echo "Converting: $PLAYLIST_PATH"
-xq -x /playlist/trackList/track/location "$PLAYLIST_PATH" | sed "s|^file://||;s|^${BASE_MUSIC_PATH}|..|" | python3 -c "import sys; from urllib.parse import unquote; print(unquote(sys.stdin.read()));" > "$OUTPUT_PATH"
-echo "Written to: $OUTPUT_PATH"
+for x in $xs; do
+	PLAYLIST_PATH="$QL_PLAYLIST_PATH/$x.xspf"
+	[ ! -f "$PLAYLIST_PATH" ] && echo "Invalid playlist: $x" && exit 1
+	OUTPUT_PATH="$BASE_MUSIC_PATH/Playlists/$x.m3u"
+
+	echo "Converting: $PLAYLIST_PATH"
+	xq -x /playlist/trackList/track/location "$PLAYLIST_PATH" | sed "s|^file://||;s|^${BASE_MUSIC_PATH}|..|" | python3 -c "import sys; from urllib.parse import unquote; print(unquote(sys.stdin.read()));" > "$OUTPUT_PATH"
+	echo "Written to: $OUTPUT_PATH"
+done
